# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0569b710c1aa7c714aeb004e6e603e648011b8bca9dca478ca0537a76327b0db0f3e18f99c501af01b7cf5d097c8f116b6e934aa16a51f4f6c8d5ca98798b458

test:
  secret_key_base: 136e02838e11f6b2d475a155e8b19ec7c6be1d1d9c8b580125706aaabf756719f7d264b62b6aba407b7e58a3e64e25c62bdc0ceaed88d346defc057f1f35fb7c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
